name: app
description: Polkawallet built with Flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.3+2031

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^1.1.0+2
  flutter_svg: ^0.19.3
  json_annotation: ^3.1.0
  get_storage: ^1.3.2
  biometric_storage: 1.0.1+5
  update_app: ^0.1.5
  device_info: ^0.4.2
  polkawallet_plugin_kusama:
    git:
      url: https://github.com/polkawallet-io/polkawallet_plugin_kusama.git
      ref: a4ae23cc229016babf82fb0e6c85a6cb46ec16a3
#    path: ../../coding/polkawallet/polkawallet_plugin_kusama
  polkawallet_plugin_acala:
    git:
      url: https://github.com/AcalaNetwork/polkawallet_plugin_acala.git
      ref: 8714c27a4f46e3f0277ab58b42eea547f7d33095
#    path: ../../coding/polkawallet/polkawallet_plugin_acala
  polkawallet_plugin_laminar:
    git:
      url: https://github.com/polkawallet-io/polkawallet_plugin_laminar.git
      ref: a6bcda75198f64b70e0f13f6c71f067b72d536b0
#    path: ../../coding/polkawallet/polkawallet_plugin_laminar
  polkawallet_plugin_chainx:
    git:
      url: https://github.com/true-eye/polkawallet_plugin_chainx.git
      ref: 07b601d0aaae0b173e7a18006f7502b9bb55b32d
#    path: ../../coding/polkawallet/polkawallet_plugin_chainx
  polkawallet_plugin_edgeware:
    git:
      url: https://github.com/remzrn/polkawallet_plugin_edgeware.git
      ref: acdfd8bddce2075542e4678ef55855805700c752
#    path: ../../coding/polkawallet/polkawallet_plugin_edgeware

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  polkawallet_ui:
    git:
      url: https://github.com/polkawallet-io/ui.git
      ref: 51ebe9ffe2c9a0c524aadffc03cbe413d891fa57
#    path: ../../coding/polkawallet/ui
  polkawallet_sdk: ^0.1.5
#  polkawallet_sdk:
#    path: ../../coding/polkawallet/sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  mobx_codegen: ^1.1.2
  json_serializable: ^3.5.0
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo_about.png
    - assets/images/nav_assets.svg
    - assets/images/nav_profile.svg
    - assets/images/screenshot.png
    - assets/images/scan.svg
    - assets/images/assets_up.svg
    - assets/images/assets_down.svg
    - assets/images/tx_failed.svg
    - assets/images/assets_send.png
    - assets/images/wallet_connect_logo.png
    - assets/images/wallet_connect_banner.png
    - assets/images/network_icon_bg.svg
    - assets/images/network_icon_border.svg
    - assets/images/menu.svg
    - assets/images/qr.svg
    - assets/images/scan.svg
    - assets/images/public/guide_0.png
    - assets/images/public/guide_1.png
    - assets/images/public/guide_2.png
    - assets/images/public/guide_3.png
    - assets/images/public/guide_4.png
    - assets/images/public/banner_kar_plo.png
    - assets/images/public/kar_bg.png
    - assets/images/public/kar_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue.otf
          weight: 700
